server.port=8080
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#show sql queries
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

dms.app.jwtSecret=be0637138fc4196320f8f6030aab1705
dms.app.jwtExpirationMs=30000
dms.app.jwtCookieName=jwtCookie

# enable ansi colors in console output
spring.output.ansi.enabled=ALWAYS




