server.address=0.0.0.0
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# cloud MYSQL database
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.url=${DB_URL}

# local MYSQL database
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=jdbc:mysql://localhost:3306/dms

# cloud NOSQL database
#spring.data.mongodb.uri=mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@cluster0.jfzutol.mongodb.net//dms-db

# local NOSQL database
spring.data.mongodb.uri=mongodb://localhost:27017/dms-db


#show sql queries
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true



spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

dms.app.access.jwtSecret=${secretKey_1}
dms.app.refresh.jwtSecret=${secretKey_2}

dms.app.jwtExpirationMs=3600000
dms.app.jwtRefreshExpirationMs=86400000
dms.app.jwtCookieName=jwtCookie

# enable ansi colors in console output
spring.output.ansi.enabled=ALWAYS

# upload files
spring.servlet.multipart.max-file-size=10GB
spring.servlet.multipart.max-request-size=10GB

# page size var
spring.data.mongodb.page-size=20

# local folder path
local.folder.path=E:\\06_Java\\Fullstack-dms\\Backend-SpringBoot\\UsersUploads






