server.port=8080
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver


#spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#show sql queries
#spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

dms.app.access.jwtSecret=be0637138fc4196320f8f6030aab1705
dms.app.refresh.jwtSecret=cd2ae4cf061bef1552af16d6e9b9102e083dbf16fc8d5a63812ff04a
dms.app.jwtExpirationMs=3600000
#dms.app.jwtExpirationMs=10000
dms.app.jwtRefreshExpirationMs=86400000
dms.app.jwtCookieName=jwtCookie

# enable ansi colors in console output
spring.output.ansi.enabled=ALWAYS




